### PR TITLE
Proposal: Support rooted wildcard paths

### LINKED ISSUE #159: Globbing pattern do not work with fully qualified paths
The `test` command of the [Azure Pipelines .NET Core CLI task](https://docs.microsoft.com/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops) places result files in `$(Agent.TempDirectory)` so I'd like to upload my code coverage reports with `dotnet tool run codecov -- -f "$(Agent.TempDirectory)\*\coverage.cobertura.xml" --required`.

`Glob.Files` doesn't work with full paths.

### PR DESCRIPTION
**Pull request by nxtn**
Fixes #159

### CODE REVIEW

File: Source/Codecov/Coverage/Tool/Coverage.cs [hunk 1]
```diff
@@ -67,7 +76,7 @@ private IEnumerable<ReportFile> LoadReportFile()
                         ? expanded
                         : Enumerable.Empty<string>())
                 .Select(x => new ReportFile(x, File.ReadAllText(x))).ToArray();
-            if (report?.Any() != true)
+            if (report.Length == 0)
```
Comment (AdmiringWorm) [inline Source/Codecov/Coverage/Tool/Coverage.cs]: Don't remove the question mark here, at this point the report **CAN** still be null.

**Review by AdmiringWorm — CHANGES_REQUESTED** [review]
Overall looks good, just 1 minor thing to fix.

File: Source/Codecov/Coverage/Tool/Coverage.cs (hunk 1 above)
Comment (nxtn) [reply Source/Codecov/Coverage/Tool/Coverage.cs:79]: Any input or output of LINQ methods can not be `null`. If `Enumerable.Empty` is supplied, `Select` returns `Enumerable.Empty` and `ToArray` returns `Array.Empty`; if `null` is supplied you'll just get an `ArgumentNullException`. You can see this clearly with `#nullable enable`.

Comment (nxtn) [reply Source/Codecov/Coverage/Tool/Coverage.cs]: Yeah, I missed the first question mark in the call chain.

Comment (nxtn) [reply Source/Codecov/Coverage/Tool/Coverage.cs]: Not exactly. As per CommandLineParser docs:

> The IEnumerables are initialized to empty arrays rather than null.

IEnumerables in .NET are usually non-nullable.

Comment (AdmiringWorm) [reply Source/Codecov/Coverage/Tool/Coverage.cs]: > Not exactly. As per CommandLineParser docs:

Yes, their docs say that. However, I have had cases in the past where it would still be set to null. So having a null check here is still required.

> IEnumerables in .NET are usually non-nullable.

Typically yes, but there is nothing stopping it from being null (especially when the program/library isn't marked with the nullable attribute).

**Review by AdmiringWorm — APPROVED** [review]
LGTM

**Comment by AdmiringWorm** [comment]
@nxtn your changes have been merged, thanks for your contribution 👍

I plan to make a new release a bit later this week if everything goes according to plan.
